### PR TITLE
Uk with compiled release

### PR DESCRIPTION
**Pull request by yolile**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Isn't the intention to delete all fetch.py scripts from here, and use ocdsdata instead?

**Comment by jpmckinney** [comment]
@yolile Have these changes been made to ocdsdata? If not, should an issue be created there?

I have the same questions about the `paraguay-hacienda-data` branch.

**Comment by jpmckinney** [comment]
cc @robredpath as FYI

**Comment by jpmckinney** [comment]
Closing issue but keeping branch for now.

**Comment by robredpath** [comment]
@jpmckinney we are testing all the new scrapers in https://github.com/open-contracting/ocdsdata/issues/100 . @odscjames - is there anything here that's relevant for the ocdsdata UK scraper?

**Pull request closed without merging**
