### PR TITLE
Remove validate.py script

### PR DESCRIPTION
**Pull request by jpmckinney**
We should be using CoVE for validation.

For basic JSON Schema validation, use [ocdskit](https://github.com/open-contracting/ocdskit).

### CODE REVIEW

**Comment by yolile** [comment]
We also have to update the README

**Comment by jpmckinney** [comment]
Good catch, done.

**Comment by jpmckinney** [comment]
I'll merge after I've written a way for CoVE's CLI to populate the validationErrors field.

**Comment by jpmckinney** [comment]
Decided to merge anyway.

**Pull request merged**
